default:
    image: 'thlmylab/swakkd:stable'

variables:
    VERSION_NUMBER: 1.0.0-alpha.$CI_PIPELINE_ID
    IMAGE_PULL_SECRET: babelfish-image-pull-secret

stages:
- prepare
- test
- build
- deploy

secrets:
    stage: prepare
    script:
    - kubectl delete secret $IMAGE_PULL_SECRET || true
    - "kubectl create secret docker-registry $IMAGE_PULL_SECRET \
                    --docker-server=$CI_REGISTRY \
                    --docker-username=image-registry \ 
                    --docker-password=$CI_REGISTRY_TOKEN"
    needs: []

test:
    stage: test
    image: python:3.10-slim
    script:
        - pip3 install virtualenv
        - virtualenv venv
        - source venv/bin/activate
        - cd backend
        - pip3 install --no-cache-dir -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
        - python -m unittest discover --p "*_test.py"
    variables:
        PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
        HUGGINGFACE_HUB_CACHE: "$CI_PROJECT_DIR/.cache/huggingface"
    cache: # cache dependencies and models
        paths:
            - .cache/pip
            - .cache/huggingface/
            - venv/
    needs: []

build-frontend-image:
    stage: build
    image: docker:stable
    services: ["docker:dind"]
    script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/babelfish-frontend:$VERSION_NUMBER frontend/
    - docker tag $CI_REGISTRY_IMAGE/babelfish-frontend:$VERSION_NUMBER $CI_REGISTRY_IMAGE/babelfish-frontend:latest
    - docker push $CI_REGISTRY_IMAGE/babelfish-frontend:$VERSION_NUMBER
    - docker push $CI_REGISTRY_IMAGE/babelfish-frontend:latest
    needs: []

build-backend-image:
    stage: build
    image: docker:stable
    services: ["docker:dind"]
    script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/babelfish-backend:$VERSION_NUMBER backend/
    - docker tag $CI_REGISTRY_IMAGE/babelfish-backend:$VERSION_NUMBER $CI_REGISTRY_IMAGE/babelfish-backend:latest
    - docker push $CI_REGISTRY_IMAGE/babelfish-backend:$VERSION_NUMBER
    - docker push $CI_REGISTRY_IMAGE/babelfish-backend:latest
    needs: []


deploy:
    stage: deploy
    script:
    - helm upgrade --set-string "imagePullSecret=$IMAGE_PULL_SECRET,backendImageTag=$VERSION_NUMBER,frontendImageTag=$VERSION_NUMBER,ingress.host=babelfish-$CI_PROJECT_ID.edu.k8s.th-luebeck.dev" --set-json 'openAPIEnabled=true,ingress.annotations={"cert-manager.io/cluster-issuer":"letsencrypt","acme.cert-manager.io/http01-edit-in-place":"true"}' babelfish helm-chart/
    needs:
      - secrets
      - build-frontend-image
      - build-backend-image
