imageRegistry: git.mylab.th-luebeck.de:4181/cloud-native/ws2022-23/cloudprog-rene-maget

backendImageTag: "" # This value defaults to .Chart.AppVersion
frontendImageTag: "" # This value defaults to .Chart.AppVersion

ingress: {}

openAPIEnabled: false