apiVersion: apps/v1
kind: Deployment
metadata:
  name: babelfish-backend
  labels:
    app: babelfish-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: babelfish-backend
  strategy:
    type: Recreate # RollingUpdate would make way more sense, but the ResourceQuota doesn't allow more than a single pod
  template:
    metadata:
      labels:
        app: babelfish-backend
    spec:
      imagePullSecrets:
        - name: "{{.Values.imagePullSecret}}"
      containers:
        - name: babelfish-backend
          image: "{{.Values.imageRegistry}}/babelfish-backend:{{.Values.backendImageTag | default .Chart.AppVersion}}"
          resources:
            limits:
              cpu: '2'
              memory: 1.5G
            requests:
              cpu: 200m
              memory: 950M
          envFrom:
            - configMapRef:
                name: babelfish-backend
          ports:
            - containerPort: 8000
