apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: babelfish
spec:
  rules:
  - host: "{{.Values.host}}"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: babelfish-backend
            port:
              number: 80
  tls:
  - secretName: babelfish-ingress-cert
    hosts:
      - "{{.Values.host}}"
