apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: babelfish
spec:
  rules:
  - host: "{{.Values.host}}"
    http:
      paths:
        - path: /translate
          pathType: Exact
          backend:
            service:
              name: babelfish-backend
              port:
                number: 80
        - path: /
          pathType: Prefix
          backend:
            service:
              name: babelfish-frontend
              port:
                number: 80
  tls:
  - secretName: babelfish-ingress-cert
    hosts:
      - "{{.Values.host}}"
